---
title: "練習1"
date: "2018-10-22"
output: html_document
params:
  studentID: "410773018"
  studentName: "王媺涵"
---
存檔時，請用你的學號當延伸檔名。例如：若你的學號為41078392，則請`File->Save As...`存成Exercise1-41078392.Rmd。

## 1
引入[五大銀行一個月定存固定利率歷史月資料](https://raw.githubusercontent.com/tpemartin/github-data/master/bankdata.csv)。

```{r}
library(readr)
bankdata <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/bankdata.csv")
```

### 1.1
將**銀行**變數改成factor
```{r ans11}
library(stringr)
as.factor(bankdata$"銀行")->bankdata$"銀行"
```

### 1.2
將年月改成西元年月
```{r ans12}
library(readr)
library(stringr)
library(lubridate)
Year<-str_sub(bankdata$"年月",1,3)
Month<-str_sub(bankdata$"年月",5,6)
Year<-as.integer(Year)
Year<-Year + 1911
Year<-as.character(Year)
str_c(Year,"/",Month)->bankdata$"年月"
```

## 2
Google天災地圖會發佈天災時地資訊，如[潭美颱風(Typhoon Trami)](https://google.org/crisismap/google.com/2018-trami)，但它的時間是以UTC表示，如"2018/30/09 00:00 UTC",試透過`lubridate::with_tz()`將"2018/30/09 00:00 UTC"轉成台灣時間。(Hint: 台灣tzone可用`grep("Taipei",OlsonNames(),value=TRUE)`指令查得)

```{r ans2}
library(lubridate)
 x <- ydm_hm("2018/30/09 00:00", tz="UTC")
  with_tz(x, "Asia/Taipei")
grep("Taipei",OlsonNames(),value=TRUE)
```



```{r}
x <- ymd_hms("2009-08-07 00:00:01", tz = "America/New_York")
with_tz(x, "GMT")
```


